import os
print(os.getcwd())
print("*********************")
print(os.listdir())
print("*********************")
print(os.path)
#os.mkdir('giri_1')
print("*********************")
print(os.listdir())
print("*********************")
##os.rmdir("giri_1")
print("*********************")
print(os.listdir())
os.remove('setname.py')
print(os.listdir())